In [ ]:
# 2D array 
rows, cols = (5, 5) 
arr=[] 
for i in range(cols): 
    col = [] 
    for j in range(rows): 
        col.append(0) 
    arr.append(col) 
print(arr) 

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


In [ ]:
for x in range(m):  # no of rows
  for y in  range(n):    # no of columns
      print("1", end=" ")
  print("\n")

SyntaxError: ignored

#Linear Algebra
### Scalars, Vectors, Matrices, and Tensors

This first project supplements the content covered are, "Scalars, Vectors, Matrices, and Tensors".  We will cover the basics of linear algebra and start practicing notation and simple operations. We will be using NumPy, the fundamental package for scientific computing with Python, to create and manipulate arrays. 

### 1. Getting Started With NumPy

To ensure you have the library installed correctly, import NumPy and print the version number using the cell below. 

In [ ]:
https://numpy.org/doc/stable/reference/generated/numpy.dot.html

In [ ]:
#sys module provides information about constants, functions 
#and methods of the Python interpreter.

In [ ]:
import sys
import numpy as np

print 'Python: {}'.format(sys.version)
print 'NumPy: {}'.format(np.__version__)

Python: 2.7.17 (default, Sep 30 2020, 13:38:04) 
[GCC 7.5.0]
NumPy: 1.16.4


To defining a scalar, which is a single number or value, simply use an equal sign in python.

In [ ]:
# a scalar
x = 6
x

6

With NumPy, a vector can be defined using a simple array function.

In [ ]:
# a vector
x = np.array((1,2,3))
x

array([1, 2, 3])

NumPy arrays have attributes that can tell us helpful information, such as the shape or size of the vector.

In [ ]:
print 'Vector dimensions: {}'.format(x.shape)
print 'Vector size: {}'.format(x.size)

Vector dimensions: (3,)
Vector size: 3


In [ ]:
xx=x.reshape(-1, 3)
xx.shape
xx

array([[1, 2, 3]])

Defining a matrix is just as easy! Simply use brackets and commas to separate rows. 

In [ ]:
x = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
print 'Matrix dimensions: {}'.format(x.shape)
print 'Matrix size: {}'.format(x.size)

Matrix dimensions: (3, 3)
Matrix size: 9


NumPy makes it easy to quickly define arrays using the desired dimensions. For example, if we wanted to make a 3x3 matrix, we could issue the command in the follow cell:

In [ ]:
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
print 'Matrix dimensions: {}'.format(x.shape)
print 'Matrix size: {}'.format(x.size)

Matrix dimensions: (3, 3)
Matrix size: 9


While it's harder to visualize as the number of axes goes up, it's trivial in NumPy to define a tensor of higher dimensions. For example, a 3-D tensor is created by the following cell. 4-D, 5-D, and 6-D tensors are just as easy to define! 

In [ ]:
x = np.ones((3,3,3))
x

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
print 'Tensor dimensions: {}'.format(x.shape)
print 'Tensor size: {}'.format(x.size)

Tensor dimensions: (3, 3, 3)
Tensor size: 27


### 2. Indexing

Familiarize yourself with NumPy's indexing conventions using the following cells

In [ ]:
A = np.ones((5,5), dtype = np.int)
print A

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
A[0:1,2:4]

In [ ]:
# indexing starts at 0
A[0,1] = 2
print A

[[1 2 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
# Note! NumPy using rows, columns convention
# assign entire rows or columns using a :
A[:,0] = 3
print A

[[[3 3 3 3 3]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[3 3 3 3 3]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[3 3 3 3 3]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[3 3 3 3 3]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[3 3 3 3 3]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# for higher dimensions, simply add an index
A = np.ones((5,5,5), dtype = np.int)

# assign first row a new value
A[:,0,0] = 6
print A

[[[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


### 3. Matrix Operations

Let's practice matrix addition, subtraction, and multiplication.

In [ ]:
A = np.matrix([[1,2],[3,4]])
B = np.ones((2,2), dtype = np.int)

In [ ]:
print A

[[1 2]
 [3 4]]


In [ ]:
print B

[[1 1]
 [1 1]]


In [ ]:
# Element-wise sum
C = A + B
print C

[[2 3]
 [4 5]]


In [ ]:
# Element-wise subtraction
C = A - B
print C

[[0 1]
 [2 3]]


In [ ]:
# matrix multiplication
C = A*B
print C

[[3 3]
 [7 7]]


In [ ]:
np.dot(3, 4)

12

In [ ]:
np.dot(A,B)

matrix([[3, 3],
        [7, 7]])

In [ ]:
np.dot([2j, 3j], [2j, 3j])

(-13+0j)

In [ ]:
https://numpy.org/doc/stable/reference/generated/numpy.dot.html

### 4. The Matrix Transpose

A transpose is used to flip the rows and columns of an array.  Using NumPy, finding the transpose of a matrix is quick and efficient.

In [ ]:
A = np.array(range(9))
A = A.reshape(3,3)
print A

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# calculate tranpose of A
B = A.T
print B

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [ ]:
# taking the tranpose twice will return the original matrix
C = B.T
print C

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# The transpose will work arrays of any dimension
A = np.array(range(10))
A = A.reshape(2,5)
print A

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
# create a column vector by taking the transpose
B = A.T
print B

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


### 5. Tensors with Higher Dimensions!

While it's very difficult to visualize higher dimensions, NumPy can handle arrays that have any dimensions.  To demonstrate this, create an array with ten dimensions in the cell below.

In [ ]:
A = np.ones((3,3,3,3,3,3,3,3,3,3))

In [ ]:
print A.shape
print(len(A.shape))
print A.size

(3, 3, 3, 3, 3, 3, 3, 3, 3, 3)
10
59049
